import type { StaffRole } from '@petshop/shared'
import {
  ALL_PERMISSION_CODES,
  LEGACY_PERMISSION_ALIASES,
  expandPermissionCodes,
} from './permission-catalog.web'

export type Permission = string

export const PERMISSIONS = Object.freeze(
  Object.fromEntries(
    ALL_PERMISSION_CODES.map((code) => [code.toUpperCase().replace(/[.:]/g, '_'), code]),
  ) as Record<string, Permission>,
)

const ROLE_PERMISSIONS: Record<StaffRole, Permission[]> = {
  SUPER_ADMIN: [...ALL_PERMISSION_CODES, 'FULL_BRANCH_ACCESS'],
  ADMIN: [
    'dashboard.read',
    'daily_report.read',
    'product.read',
    'product.create',
    'product.update',
    'product.delete',
    'product.export',
    'service.read',
    'service.create',
    'service.update',
    'service.delete',
    'supplier.read',
    'supplier.create',
    'supplier.update',
    'supplier.delete',
    'stock_receipt.read',
    'stock_receipt.create',
    'stock_receipt.update',
    'stock_receipt.pay',
    'stock_receipt.receive',
    'stock_receipt.complete',
    'stock_receipt.cancel',
    'stock_receipt.return',
    'stock_receipt.import',
    'stock_receipt.export',
    'stock_transfer.read',
    'stock_transfer.create',
    'stock_transfer.update',
    'stock_transfer.confirm',
    'stock_transfer.receive',
    'stock_transfer.cancel',
    'stock_transfer.import',
    'stock_transfer.export',
    'stock_audit.read',
    'stock_audit.create',
    'stock_audit.update',
    'stock_audit.delete',
    'stock_audit.balance',
    'stock_audit.import',
    'stock_audit.export',
    'cost_adjustment.read',
    'cost_adjustment.create',
    'cost_adjustment.update',
    'cost_adjustment.apply',
    'customer.read.all',
    'customer.create',
    'customer.update',
    'customer.delete',
    'pet.read',
    'pet.create',
    'pet.update',
    'pet.delete',
    'grooming.read',
    'grooming.create',
    'grooming.update',
    'grooming.start',
    'grooming.complete',
    'grooming.cancel',
    'hotel.read',
    'hotel.create',
    'hotel.update',
    'hotel.checkin',
    'hotel.checkout',
    'hotel.cancel',
    'order.read.all',
    'order.create',
    'order.update',
    'order.approve',
    'order.cancel',
    'order.ship',
    'order.pay',
    'order_return.read',
    'order_return.create',
    'order_return.cancel',
    'order_return.receive',
    'order_return.pay',
    'shipping_reconciliation.read',
    'shipping_reconciliation.create',
    'shipping_reconciliation.update',
    'shipping_reconciliation.confirm',
    'shipping_reconciliation.cancel',
    'shipping_reconciliation.pay',
    'shipping_reconciliation.import',
    'shipping_reconciliation.export',
    'shipping_partner.read',
    'receipt.read',
    'receipt.create',
    'receipt.update',
    'receipt.cancel',
    'payment.read',
    'payment.create',
    'payment.update',
    'payment.cancel',
    'report.sales',
    'report.inventory',
    'report.purchase',
    'report.profit',
    'report.customer',
    'report.debt',
    'report.cashbook',
    'branch.read',
    'branch.create',
    'branch.update',
    'staff.read',
    'staff.create',
    'staff.update',
    'staff.deactivate',
    'role.read',
    'role.create',
    'role.update',
    'settings.app.read',
    'settings.app.update',
    'settings.audit_log.read',
    'settings.pricing_policy.manage',
    'settings.payment.manage',
    'settings.template.manage',
    'settings.order_flow.manage',
    'settings.return_reason.manage',
    'sales_channel.pos',
    'sales_channel.web',
    'sales_channel.social',
    'sales_channel.online_order',
    'sales_channel.marketplace',
    'sales_channel.grabmart',
    'promotion.config',
    'promotion.read',
    'promotion.create',
    'promotion.update',
    'loyalty.manage',
    'invoice.electronic.manage',
    'FULL_BRANCH_ACCESS',
  ],
  MANAGER: [
    'dashboard.read',
    'daily_report.read',
    'product.read',
    'product.create',
    'product.update',
    'product.export',
    'service.read',
    'service.create',
    'service.update',
    'supplier.read',
    'supplier.create',
    'supplier.update',
    'stock_receipt.read',
    'stock_receipt.create',
    'stock_receipt.update',
    'stock_receipt.pay',
    'stock_receipt.receive',
    'stock_receipt.complete',
    'stock_receipt.export',
    'stock_transfer.read',
    'stock_transfer.create',
    'stock_transfer.update',
    'stock_transfer.confirm',
    'stock_transfer.receive',
    'stock_transfer.export',
    'stock_audit.read',
    'stock_audit.create',
    'stock_audit.update',
    'stock_audit.balance',
    'stock_audit.export',
    'customer.read.all',
    'customer.create',
    'customer.update',
    'pet.read',
    'pet.create',
    'pet.update',
    'grooming.read',
    'grooming.create',
    'grooming.update',
    'grooming.start',
    'grooming.complete',
    'hotel.read',
    'hotel.create',
    'hotel.update',
    'hotel.checkin',
    'hotel.checkout',
    'order.read.all',
    'order.create',
    'order.update',
    'order.approve',
    'order.cancel',
    'order.ship',
    'order.pay',
    'order_return.read',
    'order_return.create',
    'order_return.cancel',
    'order_return.receive',
    'order_return.pay',
    'shipping_reconciliation.read',
    'shipping_reconciliation.create',
    'shipping_reconciliation.update',
    'shipping_reconciliation.confirm',
    'shipping_reconciliation.pay',
    'shipping_reconciliation.export',
    'receipt.read',
    'receipt.create',
    'receipt.update',
    'payment.read',
    'payment.create',
    'payment.update',
    'report.sales',
    'report.inventory',
    'report.purchase',
    'report.profit',
    'report.customer',
    'report.debt',
    'report.cashbook',
    'staff.read',
    'settings.app.read',
    'settings.audit_log.read',
    'promotion.read',
    'promotion.create',
    'promotion.update',
    'loyalty.manage',
  ],
  STAFF: [
    'dashboard.read',
    'product.read',
    'service.read',
    'customer.read.assigned',
    'customer.create',
    'customer.update',
    'pet.read',
    'pet.create',
    'pet.update',
    'grooming.read',
    'grooming.update',
    'hotel.read',
    'hotel.update',
    'order.read.assigned',
    'order.create',
    'order.update',
    'order.pay',
    'order_return.read',
    'order_return.create',
    'receipt.read',
    'receipt.create',
    'payment.read',
    'payment.create',
  ],
  VIEWER: [
    'dashboard.read',
    'product.read',
    'service.read',
    'customer.read.assigned',
    'pet.read',
    'grooming.read',
    'hotel.read',
    'order.read.assigned',
    'receipt.read',
    'payment.read',
    'report.sales',
    'report.inventory',
    'report.customer',
    'report.cashbook',
  ],
}

export const getRolePermissions = (role: StaffRole): Permission[] => {
  return ROLE_PERMISSIONS[role] ?? []
}

export const resolvePermissions = (permissions: string[]): Permission[] => {
  return expandPermissionCodes(permissions)
}

export const satisfiesPermission = (permissions: string[], requiredPermission: string): boolean => {
  const resolvedPermissions = new Set(resolvePermissions(permissions))
  if (resolvedPermissions.has(requiredPermission)) return true

  const mappedChildren = LEGACY_PERMISSION_ALIASES[requiredPermission]
  return mappedChildren ? mappedChildren.every((permission) => resolvedPermissions.has(permission)) : false
}

export const hasAnyPermission = (permissions: string[], requiredPermissions: string[]): boolean => {
  return requiredPermissions.some((permission) => satisfiesPermission(permissions, permission))
}

export const hasPermission = (role: StaffRole, permission: Permission): boolean => {
  return satisfiesPermission(getRolePermissions(role), permission)
}
